default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: doadmin
  password: AVNS_HNFwByh6WPkLC_-dHNy
  host: elevador-do-user-17223022-0.b.db.ondigitalocean.com
  port: 25060
  database: defaultdb
  sslmode: REQUIRED

development:
  <<: *default
  database: defaultdb

test:
  <<: *default
  database: defaultdb

production:
  <<: *default
  database: defaultdb
  username: doadmin
  password: AVNS_HNFwByh6WPkLC_-dHNy
  host: elevador-do-user-17223022-0.b.db.ondigitalocean.com
  port: 25060
  sslmode: REQUIRED
